version: "3.9"

services:
  # Nginx apenas, com configuração via conf.d
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    restart: unless-stopped

  # PostgreSQL 17.6
  postgres:
    image: postgres:17.6
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hotspot}
      POSTGRES_USER: ${POSTGRES_USER:-hotspot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hotspotpass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis latest
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
