version: "3.9"

services:
  # Controladora Unifi
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=512M
      - MEM_STARTUP=512M
    volumes:
      - ./unifi/config:/config
    ports:
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "1900:1900/udp"
      - "8843:8843"
      - "8880:8880"
      - "6789:6789"
      - "5514:5514/udp"
    restart: unless-stopped

  # FreeRADIUS para autenticação
  freeradius:
    image: freeradius/freeradius-server:latest
    container_name: freeradius
    volumes:
      - ./freeradius:/etc/raddb
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    restart: unless-stopped

  # Banco de dados PostgreSQL
  db:
    image: postgres:13-alpine
    container_name: hotspot-db
    environment:
      POSTGRES_DB: hotspot
      POSTGRES_USER: hotspot
      POSTGRES_PASSWORD: ${DB_PASSWORD:-hotspotpass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Nest API (backend Node)
  nest-api:
    image: node:18-alpine
    container_name: nest-api
    working_dir: /app
    volumes:
      - ./BACKEND/nest-api:/app
    command: sh -c "npm ci && npm run dev"
    environment:
      API_PORT: ${API_PORT:-3000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://hotspot:${DB_PASSWORD:-hotspotpass}@db:5432/hotspot}
      RADIUS_SECRET: ${RADIUS_SECRET:-radiussecret}
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "3000:3000"
    depends_on:
      - db
      - freeradius
    restart: unless-stopped

  # FastAPI (Python)
  fastapi:
    image: python:3.11-slim
    container_name: fastapi-app
    working_dir: /app
    volumes:
      - ./BACKEND/fastapi-app:/app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python -m uvicorn main:app --host 0.0.0.0 --port 3001"
    environment:
      SECRET_KEY: ${SECRET_KEY:-changeme}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      UNIFI_CONTROLLER_URL: ${UNIFI_CONTROLLER_URL:-http://unifi-controller:8443}
      UNIFI_USER: ${UNIFI_USER:-admin}
      UNIFI_PASSWORD: ${UNIFI_PASSWORD:-password}
    ports:
      - "3001:3001"
    depends_on:
      - unifi-controller
    restart: unless-stopped

  # Frontend (Vite)
  frontend:
    image: node:18-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./FRONTEND:/app
    command: sh -c "npm ci && npm run dev"
    environment:
      VITE_API_PROXY: ${VITE_API_PROXY:-/api}
      VITE_PYAPI_PROXY: ${VITE_PYAPI_PROXY:-/pyapi}
    ports:
      - "5173:5173"
    depends_on:
      - nest-api
      - fastapi
    restart: unless-stopped

  # Nginx (reverse proxy)
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - nest-api
      - fastapi
    restart: unless-stopped

volumes:
  postgres_data:
